# Configurações do servidor
server.port=8080

# Configurações do MySQL (Ajuste o nome do banco, usuário e senha para os seus)
spring.datasource.url=jdbc:mysql://localhost:3306/db_treinos
spring.datasource.username=root
spring.datasource.password=sua_senha_aqui
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true